/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.book_ngr_idx.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ISchema : Serializable {
    val name: String?
    val fieldType: String?
    val stored: Boolean?
    val indexed: Boolean?
    val fast: Boolean?
    val fieldnorms: Boolean?
    val expandDots: Boolean?
    val tokenizer: String?
    val record: String?
    val normalizer: String?
}
