/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Genre(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?,
    parentPath: InverseForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?,
    aliased: Table<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>(
    alias,
    io.github.asm0dey.opdsko.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.genre</code>
         */
        val GENRE: Genre = Genre()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord> = io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord::class.java

    /**
     * The column <code>public.genre.id</code>.
     */
    val ID: TableField<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.genre.name</code>.
     */
    val NAME: TableField<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.genre</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.genre</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.genre</code> table reference
     */
    constructor(): this(DSL.name("genre"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?, parentPath: InverseForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GENRE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GenrePath : Genre, Path<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?, parentPath: InverseForeignKey<out Record, io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>): super(alias, aliased)
        override fun `as`(alias: String): GenrePath = GenrePath(DSL.name(alias), this)
        override fun `as`(alias: Name): GenrePath = GenrePath(alias, this)
        override fun `as`(alias: Table<*>): GenrePath = GenrePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else io.github.asm0dey.opdsko.jooq.`public`.Public.PUBLIC
    override fun getIdentity(): Identity<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord, Long?> = super.getIdentity() as Identity<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord> = io.github.asm0dey.opdsko.jooq.`public`.keys.GENRE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<io.github.asm0dey.opdsko.jooq.`public`.tables.records.GenreRecord>> = listOf(io.github.asm0dey.opdsko.jooq.`public`.keys.GENRE_NAME_KEY)

    private lateinit var _bookGenre: io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BookGenrePath

    /**
     * Get the implicit to-many join path to the <code>public.book_genre</code>
     * table
     */
    fun bookGenre(): io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BookGenrePath {
        if (!this::_bookGenre.isInitialized)
            _bookGenre = io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BookGenrePath(this, null, io.github.asm0dey.opdsko.jooq.`public`.keys.BOOK_GENRE__BOOK_GENRE_GENRE_ID_FKEY.inverseKey)

        return _bookGenre;
    }

    val bookGenre: io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BookGenrePath
        get(): io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BookGenrePath = bookGenre()
    override fun `as`(alias: String): Genre = Genre(DSL.name(alias), this)
    override fun `as`(alias: Name): Genre = Genre(alias, this)
    override fun `as`(alias: Table<*>): Genre = Genre(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Genre = Genre(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Genre = Genre(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Genre = Genre(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Genre = Genre(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Genre = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Genre = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Genre = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Genre = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Genre = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Genre = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Genre = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Genre = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Genre = where(DSL.notExists(select))
}
