/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.`public`.tables.records


import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookGenreRecord private constructor() : TableRecordImpl<BookGenreRecord>(io.github.asm0dey.opdsko.jooq.`public`.tables.BookGenre.BOOK_GENRE), io.github.asm0dey.opdsko.jooq.`public`.tables.interfaces.IBookGenre {

    open override var bookId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open override var genreId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: io.github.asm0dey.opdsko.jooq.`public`.tables.interfaces.IBookGenre) {
        this.bookId = from.bookId
        this.genreId = from.genreId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookGenreRecord
     */
    constructor(bookId: Long, genreId: Long): this() {
        this.bookId = bookId
        this.genreId = genreId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookGenreRecord
     */
    constructor(value: io.github.asm0dey.opdsko.jooq.`public`.tables.pojos.BookGenre?): this() {
        if (value != null) {
            this.bookId = value.bookId
            this.genreId = value.genreId
            resetChangedOnNotNull()
        }
    }
}
