/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAuthor extends Serializable {

    /**
     * Getter for <code>author.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>author.fb2id</code>.
     */
    public String getFb2id();

    /**
     * Getter for <code>author.first_name</code>.
     */
    public String getFirstName();

    /**
     * Getter for <code>author.middle_name</code>.
     */
    public String getMiddleName();

    /**
     * Getter for <code>author.last_name</code>.
     */
    public String getLastName();

    /**
     * Getter for <code>author.nickname</code>.
     */
    public String getNickname();

    /**
     * Getter for <code>author.added</code>.
     */
    public LocalDateTime getAdded();
}
