/*
 * opdsko
 * Copyright (C) 2022  asm0dey
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBook extends Serializable {

    /**
     * Getter for <code>book.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>book.path</code>.
     */
    public String getPath();

    /**
     * Getter for <code>book.name</code>.
     */
    public String getName();

    /**
     * Getter for <code>book.date</code>.
     */
    public String getDate();

    /**
     * Getter for <code>book.added</code>.
     */
    public LocalDateTime getAdded();

    /**
     * Getter for <code>book.sequence</code>.
     */
    public String getSequence();

    /**
     * Getter for <code>book.sequence_number</code>.
     */
    public Integer getSequenceNumber();

    /**
     * Getter for <code>book.lang</code>.
     */
    public String getLang();
}
