/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBook extends Serializable {

    /**
     * Getter for <code>book.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>book.path</code>.
     */
    public String getPath();

    /**
     * Getter for <code>book.name</code>.
     */
    public String getName();

    /**
     * Getter for <code>book.date</code>.
     */
    public String getDate();

    /**
     * Getter for <code>book.added</code>.
     */
    public LocalDateTime getAdded();

    /**
     * Getter for <code>book.sequence</code>.
     */
    public String getSequence();

    /**
     * Getter for <code>book.sequence_number</code>.
     */
    public Integer getSequenceNumber();

    /**
     * Getter for <code>book.lang</code>.
     */
    public String getLang();

    /**
     * Getter for <code>book.zip_file</code>.
     */
    public String getZipFile();
}
