/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBooksFts extends Serializable {

    /**
     * Getter for <code>books_fts.name</code>.
     */
    public String getName();

    /**
     * Getter for <code>books_fts.sequence</code>.
     */
    public String getSequence();
}
