/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IBookAuthor extends Serializable {

    /**
     * Getter for <code>book_author.book_id</code>.
     */
    public Long getBookId();

    /**
     * Getter for <code>book_author.author_id</code>.
     */
    public Long getAuthorId();
}
