/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IGenre extends Serializable {

    /**
     * Getter for <code>genre.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>genre.name</code>.
     */
    public String getName();
}
