/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.records;


import io.github.asm0dey.opdsko.jooq.tables.BookGenre;
import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBookGenre;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookGenreRecord extends UpdatableRecordImpl<BookGenreRecord> implements IBookGenre {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>book_genre.book_id</code>.
     */
    public BookGenreRecord setBookId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book_genre.book_id</code>.
     */
    @Override
    public Long getBookId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book_genre.genre_id</code>.
     */
    public BookGenreRecord setGenreId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book_genre.genre_id</code>.
     */
    @Override
    public Long getGenreId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IBookGenre from) {
        setBookId(from.getBookId());
        setGenreId(from.getGenreId());
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookGenreRecord
     */
    public BookGenreRecord() {
        super(BookGenre.BOOK_GENRE);
    }

    /**
     * Create a detached, initialised BookGenreRecord
     */
    public BookGenreRecord(Long bookId, Long genreId) {
        super(BookGenre.BOOK_GENRE);

        setBookId(bookId);
        setGenreId(genreId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BookGenreRecord
     */
    public BookGenreRecord(io.github.asm0dey.opdsko.jooq.tables.pojos.BookGenre value) {
        super(BookGenre.BOOK_GENRE);

        if (value != null) {
            setBookId(value.getBookId());
            setGenreId(value.getGenreId());
            resetChangedOnNotNull();
        }
    }
}
