/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.`public`.routines.references


import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>public.set_limit</code>
 */
fun setLimit(
      configuration: Configuration
    , __1: Float?
): Float? {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.SetLimit()
    f.set__1(__1)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.set_limit</code> as a field.
 */
fun setLimit(
      __1: Float?
): Field<Float?> {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.SetLimit()
    f.set__1(__1)

    return f.asField()
}

/**
 * Get <code>public.set_limit</code> as a field.
 */
fun setLimit(
      __1: Field<Float?>
): Field<Float?> {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.SetLimit()
    f.set__1(__1)

    return f.asField()
}

/**
 * Call <code>public.similarity</code>
 */
fun similarity(
      configuration: Configuration
    , __1: String?
    , __2: String?
): Float? {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.Similarity()
    f.set__1(__1)
    f.set__2(__2)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.similarity</code> as a field.
 */
fun similarity(
      __1: String?
    , __2: String?
): Field<Float?> {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.Similarity()
    f.set__1(__1)
    f.set__2(__2)

    return f.asField()
}

/**
 * Get <code>public.similarity</code> as a field.
 */
fun similarity(
      __1: Field<String?>
    , __2: Field<String?>
): Field<Float?> {
    val f = io.github.asm0dey.opdsko.jooq.`public`.routines.Similarity()
    f.set__1(__1)
    f.set__2(__2)

    return f.asField()
}
