/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.references


import io.github.asm0dey.opdsko.jooq.tables.Author
import io.github.asm0dey.opdsko.jooq.tables.AuthorsFts
import io.github.asm0dey.opdsko.jooq.tables.Book
import io.github.asm0dey.opdsko.jooq.tables.BookAuthor
import io.github.asm0dey.opdsko.jooq.tables.BookGenre
import io.github.asm0dey.opdsko.jooq.tables.BooksFts
import io.github.asm0dey.opdsko.jooq.tables.Genre



/**
 * The table <code>author</code>.
 */
val AUTHOR: Author = Author.AUTHOR

/**
 * The table <code>authors_fts</code>.
 */
val AUTHORS_FTS: AuthorsFts = AuthorsFts.AUTHORS_FTS

/**
 * The table <code>book</code>.
 */
val BOOK: Book = Book.BOOK

/**
 * The table <code>book_author</code>.
 */
val BOOK_AUTHOR: BookAuthor = BookAuthor.BOOK_AUTHOR

/**
 * The table <code>book_genre</code>.
 */
val BOOK_GENRE: BookGenre = BookGenre.BOOK_GENRE

/**
 * The table <code>books_fts</code>.
 */
val BOOKS_FTS: BooksFts = BooksFts.BOOKS_FTS

/**
 * The table <code>genre</code>.
 */
val GENRE: Genre = Genre.GENRE
