/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IAuthorsFts : Serializable {
    val lastName: String?
    val firstName: String?
    val middleName: String?
    val nickname: String?
}
