/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IAuthor : Serializable {
    val id: Long?
    val fb2id: String?
    val firstName: String?
    val middleName: String?
    val lastName: String?
    val nickname: String?
    val added: LocalDateTime
}
