/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IBook : Serializable {
    val id: Long?
    val path: String
    val name: String
    val date: String?
    val added: LocalDateTime?
    val sequence: String?
    val sequenceNumber: Int?
    val lang: String?
    val zipFile: String?
    val seqid: Int?
}
