/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables;


import io.github.asm0dey.opdsko.jooq.DefaultSchema;
import io.github.asm0dey.opdsko.jooq.Indexes;
import io.github.asm0dey.opdsko.jooq.Keys;
import io.github.asm0dey.opdsko.jooq.tables.records.GenreRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genre extends TableImpl<GenreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>genre</code>
     */
    public static final Genre GENRE = new Genre();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenreRecord> getRecordType() {
        return GenreRecord.class;
    }

    /**
     * The column <code>genre.id</code>.
     */
    public final TableField<GenreRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>genre.name</code>.
     */
    public final TableField<GenreRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Genre(Name alias, Table<GenreRecord> aliased) {
        this(alias, aliased, null);
    }

    private Genre(Name alias, Table<GenreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>genre</code> table reference
     */
    public Genre(String alias) {
        this(DSL.name(alias), GENRE);
    }

    /**
     * Create an aliased <code>genre</code> table reference
     */
    public Genre(Name alias) {
        this(alias, GENRE);
    }

    /**
     * Create a <code>genre</code> table reference
     */
    public Genre() {
        this(DSL.name("genre"), null);
    }

    public <O extends Record> Genre(Table<O> child, ForeignKey<O, GenreRecord> key) {
        super(child, key, GENRE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GENRE_NAME);
    }

    @Override
    public Identity<GenreRecord, Long> getIdentity() {
        return (Identity<GenreRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GenreRecord> getPrimaryKey() {
        return Keys.GENRE__PK_GENRE;
    }

    @Override
    public List<UniqueKey<GenreRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GENRE__UK_GENRE_113431810);
    }

    @Override
    public Genre as(String alias) {
        return new Genre(DSL.name(alias), this);
    }

    @Override
    public Genre as(Name alias) {
        return new Genre(alias, this);
    }

    @Override
    public Genre as(Table<?> alias) {
        return new Genre(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Genre rename(String name) {
        return new Genre(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genre rename(Name name) {
        return new Genre(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genre rename(Table<?> name) {
        return new Genre(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
