/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.`public`.tables.pojos



/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class BookGenre(
    override val bookId: Long,
    override val genreId: Long
): io.github.asm0dey.opdsko.jooq.`public`.tables.interfaces.IBookGenre {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BookGenre = other as BookGenre
        if (this.bookId != o.bookId)
            return false
        if (this.genreId != o.genreId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.bookId.hashCode()
        result = prime * result + this.genreId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BookGenre (")

        sb.append(bookId)
        sb.append(", ").append(genreId)

        sb.append(")")
        return sb.toString()
    }
}
