/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.records


import io.github.asm0dey.opdsko.jooq.tables.BookAuthor
import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBookAuthor

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookAuthorRecord private constructor() : UpdatableRecordImpl<BookAuthorRecord>(BookAuthor.BOOK_AUTHOR), IBookAuthor {

    open override var bookId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open override var authorId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IBookAuthor) {
        this.bookId = from.bookId
        this.authorId = from.authorId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookAuthorRecord
     */
    constructor(bookId: Long, authorId: Long): this() {
        this.bookId = bookId
        this.authorId = authorId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookAuthorRecord
     */
    constructor(value: io.github.asm0dey.opdsko.jooq.tables.pojos.BookAuthor?): this() {
        if (value != null) {
            this.bookId = value.bookId
            this.authorId = value.authorId
            resetChangedOnNotNull()
        }
    }
}
