/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.daos


import io.github.asm0dey.opdsko.jooq.tables.Genre
import io.github.asm0dey.opdsko.jooq.tables.records.GenreRecord

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GenreDao(configuration: Configuration?) : DAOImpl<GenreRecord, io.github.asm0dey.opdsko.jooq.tables.pojos.Genre, Long>(Genre.GENRE, io.github.asm0dey.opdsko.jooq.tables.pojos.Genre::class.java, configuration) {

    /**
     * Create a new GenreDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.github.asm0dey.opdsko.jooq.tables.pojos.Genre): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.github.asm0dey.opdsko.jooq.tables.pojos.Genre> = fetchRange(Genre.GENRE.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.github.asm0dey.opdsko.jooq.tables.pojos.Genre> = fetch(Genre.GENRE.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.github.asm0dey.opdsko.jooq.tables.pojos.Genre? = fetchOne(Genre.GENRE.ID, value)

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfName(lowerInclusive: String, upperInclusive: String): List<io.github.asm0dey.opdsko.jooq.tables.pojos.Genre> = fetchRange(Genre.GENRE.NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    fun fetchByName(vararg values: String): List<io.github.asm0dey.opdsko.jooq.tables.pojos.Genre> = fetch(Genre.GENRE.NAME, *values)

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    fun fetchOneByName(value: String): io.github.asm0dey.opdsko.jooq.tables.pojos.Genre? = fetchOne(Genre.GENRE.NAME, value)
}
