/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBooksFts


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class BooksFts(
    override val name: String?,
    override val sequence: String?
): IBooksFts {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BooksFts = other as BooksFts
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.sequence == null) {
            if (o.sequence != null)
                return false
        }
        else if (this.sequence != o.sequence)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.sequence == null) 0 else this.sequence.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BooksFts (")

        sb.append(name)
        sb.append(", ").append(sequence)

        sb.append(")")
        return sb.toString()
    }
}
