/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq;


import io.github.asm0dey.opdsko.jooq.tables.Author;
import io.github.asm0dey.opdsko.jooq.tables.Book;
import io.github.asm0dey.opdsko.jooq.tables.BookAuthor;
import io.github.asm0dey.opdsko.jooq.tables.BookGenre;
import io.github.asm0dey.opdsko.jooq.tables.Genre;
import io.github.asm0dey.opdsko.jooq.tables.records.AuthorRecord;
import io.github.asm0dey.opdsko.jooq.tables.records.BookAuthorRecord;
import io.github.asm0dey.opdsko.jooq.tables.records.BookGenreRecord;
import io.github.asm0dey.opdsko.jooq.tables.records.BookRecord;
import io.github.asm0dey.opdsko.jooq.tables.records.GenreRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR__PK_AUTHOR = Internal.createUniqueKey(Author.AUTHOR, DSL.name("pk_author"), new TableField[] { Author.AUTHOR.ID }, true);
    public static final UniqueKey<BookRecord> BOOK__PK_BOOK = Internal.createUniqueKey(Book.BOOK, DSL.name("pk_book"), new TableField[] { Book.BOOK.ID }, true);
    public static final UniqueKey<BookRecord> BOOK__UK_BOOK_10985490 = Internal.createUniqueKey(Book.BOOK, DSL.name("uk_book_10985490"), new TableField[] { Book.BOOK.PATH }, true);
    public static final UniqueKey<BookAuthorRecord> BOOK_AUTHOR__PK_BOOK_AUTHOR = Internal.createUniqueKey(BookAuthor.BOOK_AUTHOR, DSL.name("pk_book_author"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID, BookAuthor.BOOK_AUTHOR.AUTHOR_ID }, true);
    public static final UniqueKey<BookGenreRecord> BOOK_GENRE__PK_BOOK_GENRE = Internal.createUniqueKey(BookGenre.BOOK_GENRE, DSL.name("pk_book_genre"), new TableField[] { BookGenre.BOOK_GENRE.BOOK_ID, BookGenre.BOOK_GENRE.GENRE_ID }, true);
    public static final UniqueKey<GenreRecord> GENRE__PK_GENRE = Internal.createUniqueKey(Genre.GENRE, DSL.name("pk_genre"), new TableField[] { Genre.GENRE.ID }, true);
    public static final UniqueKey<GenreRecord> GENRE__UK_GENRE_113431810 = Internal.createUniqueKey(Genre.GENRE, DSL.name("uk_genre_113431810"), new TableField[] { Genre.GENRE.NAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookAuthorRecord, AuthorRecord> BOOK_AUTHOR__FK_BOOK_AUTHOR_PK_AUTHOR = Internal.createForeignKey(BookAuthor.BOOK_AUTHOR, DSL.name("fk_book_author_pk_author"), new TableField[] { BookAuthor.BOOK_AUTHOR.AUTHOR_ID }, Keys.AUTHOR__PK_AUTHOR, new TableField[] { Author.AUTHOR.ID }, true);
    public static final ForeignKey<BookAuthorRecord, BookRecord> BOOK_AUTHOR__FK_BOOK_AUTHOR_PK_BOOK = Internal.createForeignKey(BookAuthor.BOOK_AUTHOR, DSL.name("fk_book_author_pk_book"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID }, Keys.BOOK__PK_BOOK, new TableField[] { Book.BOOK.ID }, true);
    public static final ForeignKey<BookGenreRecord, BookRecord> BOOK_GENRE__FK_BOOK_GENRE_PK_BOOK = Internal.createForeignKey(BookGenre.BOOK_GENRE, DSL.name("fk_book_genre_pk_book"), new TableField[] { BookGenre.BOOK_GENRE.BOOK_ID }, Keys.BOOK__PK_BOOK, new TableField[] { Book.BOOK.ID }, true);
    public static final ForeignKey<BookGenreRecord, GenreRecord> BOOK_GENRE__FK_BOOK_GENRE_PK_GENRE = Internal.createForeignKey(BookGenre.BOOK_GENRE, DSL.name("fk_book_genre_pk_genre"), new TableField[] { BookGenre.BOOK_GENRE.GENRE_ID }, Keys.GENRE__PK_GENRE, new TableField[] { Genre.GENRE.ID }, true);
}
