/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq;


import io.github.asm0dey.opdsko.jooq.tables.Author;
import io.github.asm0dey.opdsko.jooq.tables.AuthorsFts;
import io.github.asm0dey.opdsko.jooq.tables.Book;
import io.github.asm0dey.opdsko.jooq.tables.BookAuthor;
import io.github.asm0dey.opdsko.jooq.tables.BookGenre;
import io.github.asm0dey.opdsko.jooq.tables.BooksFts;
import io.github.asm0dey.opdsko.jooq.tables.Genre;
import io.github.asm0dey.opdsko.jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>authors_fts</code>.
     */
    public static final AuthorsFts AUTHORS_FTS = AuthorsFts.AUTHORS_FTS;

    /**
     * The table <code>book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>book_author</code>.
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>book_genre</code>.
     */
    public static final BookGenre BOOK_GENRE = BookGenre.BOOK_GENRE;

    /**
     * The table <code>books_fts</code>.
     */
    public static final BooksFts BOOKS_FTS = BooksFts.BOOKS_FTS;

    /**
     * The table <code>genre</code>.
     */
    public static final Genre GENRE = Genre.GENRE;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
