/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IAuthor;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements IAuthor {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        fb2id;
    private final String        firstName;
    private final String        middleName;
    private final String        lastName;
    private final String        nickname;
    private final LocalDateTime added;

    public Author(IAuthor value) {
        this.id = value.getId();
        this.fb2id = value.getFb2id();
        this.firstName = value.getFirstName();
        this.middleName = value.getMiddleName();
        this.lastName = value.getLastName();
        this.nickname = value.getNickname();
        this.added = value.getAdded();
    }

    public Author(
        Long          id,
        String        fb2id,
        String        firstName,
        String        middleName,
        String        lastName,
        String        nickname,
        LocalDateTime added
    ) {
        this.id = id;
        this.fb2id = fb2id;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.nickname = nickname;
        this.added = added;
    }

    /**
     * Getter for <code>author.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>author.fb2id</code>.
     */
    @Override
    public String getFb2id() {
        return this.fb2id;
    }

    /**
     * Getter for <code>author.first_name</code>.
     */
    @Override
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>author.middle_name</code>.
     */
    @Override
    public String getMiddleName() {
        return this.middleName;
    }

    /**
     * Getter for <code>author.last_name</code>.
     */
    @Override
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>author.nickname</code>.
     */
    @Override
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Getter for <code>author.added</code>.
     */
    @Override
    public LocalDateTime getAdded() {
        return this.added;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(fb2id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(middleName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(nickname);
        sb.append(", ").append(added);

        sb.append(")");
        return sb.toString();
    }
}
