/*
 * opdsko
 * Copyright (C) 2022  asm0dey
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IAuthorsFts;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorsFts implements IAuthorsFts {

    private static final long serialVersionUID = 1L;

    private final String lastName;
    private final String firstName;
    private final String middleName;
    private final String nickname;

    public AuthorsFts(IAuthorsFts value) {
        this.lastName = value.getLastName();
        this.firstName = value.getFirstName();
        this.middleName = value.getMiddleName();
        this.nickname = value.getNickname();
    }

    public AuthorsFts(
        String lastName,
        String firstName,
        String middleName,
        String nickname
    ) {
        this.lastName = lastName;
        this.firstName = firstName;
        this.middleName = middleName;
        this.nickname = nickname;
    }

    /**
     * Getter for <code>authors_fts.last_name</code>.
     */
    @Override
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>authors_fts.first_name</code>.
     */
    @Override
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>authors_fts.middle_name</code>.
     */
    @Override
    public String getMiddleName() {
        return this.middleName;
    }

    /**
     * Getter for <code>authors_fts.nickname</code>.
     */
    @Override
    public String getNickname() {
        return this.nickname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorsFts (");

        sb.append(lastName);
        sb.append(", ").append(firstName);
        sb.append(", ").append(middleName);
        sb.append(", ").append(nickname);

        sb.append(")");
        return sb.toString();
    }
}
