/*
 * opdsko
 * Copyright (C) 2022  asm0dey
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IAuthor;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements IAuthor {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        fb2id;
    private final String        firstName;
    private final String        middleName;
    private final String        lastName;
    private final String        nickname;
    private final LocalDateTime added;

    public Author(IAuthor value) {
        this.id = value.getId();
        this.fb2id = value.getFb2id();
        this.firstName = value.getFirstName();
        this.middleName = value.getMiddleName();
        this.lastName = value.getLastName();
        this.nickname = value.getNickname();
        this.added = value.getAdded();
    }

    public Author(
        Long          id,
        String        fb2id,
        String        firstName,
        String        middleName,
        String        lastName,
        String        nickname,
        LocalDateTime added
    ) {
        this.id = id;
        this.fb2id = fb2id;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.nickname = nickname;
        this.added = added;
    }

    /**
     * Getter for <code>author.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>author.fb2id</code>.
     */
    @Override
    public String getFb2id() {
        return this.fb2id;
    }

    /**
     * Getter for <code>author.first_name</code>.
     */
    @Override
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>author.middle_name</code>.
     */
    @Override
    public String getMiddleName() {
        return this.middleName;
    }

    /**
     * Getter for <code>author.last_name</code>.
     */
    @Override
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>author.nickname</code>.
     */
    @Override
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Getter for <code>author.added</code>.
     */
    @Override
    public LocalDateTime getAdded() {
        return this.added;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(fb2id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(middleName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(nickname);
        sb.append(", ").append(added);

        sb.append(")");
        return sb.toString();
    }
}
