/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBooksFts;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BooksFts implements IBooksFts {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final String sequence;

    public BooksFts(IBooksFts value) {
        this.name = value.getName();
        this.sequence = value.getSequence();
    }

    public BooksFts(
        String name,
        String sequence
    ) {
        this.name = name;
        this.sequence = sequence;
    }

    /**
     * Getter for <code>books_fts.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>books_fts.sequence</code>.
     */
    @Override
    public String getSequence() {
        return this.sequence;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BooksFts other = (BooksFts) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.sequence == null) {
            if (other.sequence != null)
                return false;
        }
        else if (!this.sequence.equals(other.sequence))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.sequence == null) ? 0 : this.sequence.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BooksFts (");

        sb.append(name);
        sb.append(", ").append(sequence);

        sb.append(")");
        return sb.toString();
    }
}
