/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBookGenre;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookGenre implements IBookGenre {

    private static final long serialVersionUID = 1L;

    private final Long bookId;
    private final Long genreId;

    public BookGenre(IBookGenre value) {
        this.bookId = value.getBookId();
        this.genreId = value.getGenreId();
    }

    public BookGenre(
        Long bookId,
        Long genreId
    ) {
        this.bookId = bookId;
        this.genreId = genreId;
    }

    /**
     * Getter for <code>book_genre.book_id</code>.
     */
    @Override
    public Long getBookId() {
        return this.bookId;
    }

    /**
     * Getter for <code>book_genre.genre_id</code>.
     */
    @Override
    public Long getGenreId() {
        return this.genreId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BookGenre other = (BookGenre) obj;
        if (this.bookId == null) {
            if (other.bookId != null)
                return false;
        }
        else if (!this.bookId.equals(other.bookId))
            return false;
        if (this.genreId == null) {
            if (other.genreId != null)
                return false;
        }
        else if (!this.genreId.equals(other.genreId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.bookId == null) ? 0 : this.bookId.hashCode());
        result = prime * result + ((this.genreId == null) ? 0 : this.genreId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookGenre (");

        sb.append(bookId);
        sb.append(", ").append(genreId);

        sb.append(")");
        return sb.toString();
    }
}
