/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.IBook;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements IBook {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        path;
    private final String        name;
    private final String        date;
    private final LocalDateTime added;
    private final String        sequence;
    private final Integer       sequenceNumber;
    private final String        lang;

    public Book(IBook value) {
        this.id = value.getId();
        this.path = value.getPath();
        this.name = value.getName();
        this.date = value.getDate();
        this.added = value.getAdded();
        this.sequence = value.getSequence();
        this.sequenceNumber = value.getSequenceNumber();
        this.lang = value.getLang();
    }

    public Book(
        Long          id,
        String        path,
        String        name,
        String        date,
        LocalDateTime added,
        String        sequence,
        Integer       sequenceNumber,
        String        lang
    ) {
        this.id = id;
        this.path = path;
        this.name = name;
        this.date = date;
        this.added = added;
        this.sequence = sequence;
        this.sequenceNumber = sequenceNumber;
        this.lang = lang;
    }

    /**
     * Getter for <code>book.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>book.path</code>.
     */
    @Override
    public String getPath() {
        return this.path;
    }

    /**
     * Getter for <code>book.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>book.date</code>.
     */
    @Override
    public String getDate() {
        return this.date;
    }

    /**
     * Getter for <code>book.added</code>.
     */
    @Override
    public LocalDateTime getAdded() {
        return this.added;
    }

    /**
     * Getter for <code>book.sequence</code>.
     */
    @Override
    public String getSequence() {
        return this.sequence;
    }

    /**
     * Getter for <code>book.sequence_number</code>.
     */
    @Override
    public Integer getSequenceNumber() {
        return this.sequenceNumber;
    }

    /**
     * Getter for <code>book.lang</code>.
     */
    @Override
    public String getLang() {
        return this.lang;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(path);
        sb.append(", ").append(name);
        sb.append(", ").append(date);
        sb.append(", ").append(added);
        sb.append(", ").append(sequence);
        sb.append(", ").append(sequenceNumber);
        sb.append(", ").append(lang);

        sb.append(")");
        return sb.toString();
    }
}
