/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables.pojos;


import io.github.asm0dey.opdsko.jooq.tables.interfaces.ISqliteSequence;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence implements ISqliteSequence {

    private static final long serialVersionUID = 1L;

    private final Object name;
    private final Object seq;

    public SqliteSequence(ISqliteSequence value) {
        this.name = value.getName();
        this.seq = value.getSeq();
    }

    public SqliteSequence(
        Object name,
        Object seq
    ) {
        this.name = name;
        this.seq = seq;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object getName() {
        return this.name;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object getSeq() {
        return this.seq;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SqliteSequence (");

        sb.append(name);
        sb.append(", ").append(seq);

        sb.append(")");
        return sb.toString();
    }
}
