name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: "*.*.*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@e2097ccd7e8ed48671dc068ac4efa86d25745b39
      with:
        arguments: build
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/libs/opdsko*all.jar
          LICENSE
