name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: "*.*.*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@5516b399405349a7d56e45a78a0bd4b3eaa62f9e
      with:
        arguments: flywayMigrate jooqCodegen build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/libs/opdsko*all.jar
          LICENSE
