/*
 * This file is generated by jOOQ.
 */
package io.github.asm0dey.opdsko.jooq.tables


import io.github.asm0dey.opdsko.jooq.DefaultSchema
import io.github.asm0dey.opdsko.jooq.tables.records.AuthorsFtsRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthorsFts(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuthorsFtsRecord>?,
    parentPath: InverseForeignKey<out Record, AuthorsFtsRecord>?,
    aliased: Table<AuthorsFtsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuthorsFtsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>authors_fts</code>
         */
        val AUTHORS_FTS: AuthorsFts = AuthorsFts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthorsFtsRecord> = AuthorsFtsRecord::class.java

    /**
     * The column <code>authors_fts.last_name</code>.
     */
    val LAST_NAME: TableField<AuthorsFtsRecord, String?> = createField(DSL.name("last_name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>authors_fts.first_name</code>.
     */
    val FIRST_NAME: TableField<AuthorsFtsRecord, String?> = createField(DSL.name("first_name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>authors_fts.middle_name</code>.
     */
    val MIDDLE_NAME: TableField<AuthorsFtsRecord, String?> = createField(DSL.name("middle_name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>authors_fts.nickname</code>.
     */
    val NICKNAME: TableField<AuthorsFtsRecord, String?> = createField(DSL.name("nickname"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<AuthorsFtsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuthorsFtsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuthorsFtsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>authors_fts</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>authors_fts</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>authors_fts</code> table reference
     */
    constructor(): this(DSL.name("authors_fts"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun `as`(alias: String): AuthorsFts = AuthorsFts(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthorsFts = AuthorsFts(alias, this)
    override fun `as`(alias: Table<*>): AuthorsFts = AuthorsFts(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthorsFts = AuthorsFts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthorsFts = AuthorsFts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthorsFts = AuthorsFts(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AuthorsFts = AuthorsFts(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AuthorsFts = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AuthorsFts = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AuthorsFts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AuthorsFts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AuthorsFts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AuthorsFts = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AuthorsFts = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AuthorsFts = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AuthorsFts = where(DSL.notExists(select))
}
